### PR TITLE
docs: readme

### PR DESCRIPTION
**Pull request by Olexandr88**
Changed the previous link was incorrect. I think it will be better that way

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [x] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-
-
-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

### CODE REVIEW

**Comment by gaetbout** [comment]
This doesn't solve any issue

**Comment by Olexandr88** [comment]
> This doesn't solve any issue

You better know. But you probably did not pay attention to the fact that the link to your questions does not reflect either open or closed questions

**Comment by gaetbout** [comment]
Which is correct, it should open the tab with the issues having the label "help wanted"

**Comment by Olexandr88** [comment]
> Which is correct, it should open the tab with the issues having the label "help wanted"

Then I'm sorry to bother you

**Comment by gaetbout** [comment]
No issue :)

**Pull request closed without merging**
