### PR TITLE
Fix: `i257` negative zeros

### PR DESCRIPTION
**Pull request by delaaxe**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-
-
-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

### CODE REVIEW

**Review by LucasLvy — CHANGES_REQUESTED** [review]
I think that for clarity in error messages you shouldn't use the regular `Add` trait of `u256` but rather [this](https://github.com/starkware-libs/cairo/blob/fe0ca27d38b44e60b1d1653c0dbf12199fe80d59/corelib/src/integer.cairo#L1066-L1116) and use `.expect("useful error message")` on the result

**Comment by delaaxe** [comment]
> I think that for clarity in error messages you shouldn't use the regular `Add` trait of `u256` but rather [this](https://github.com/starkware-libs/cairo/blob/fe0ca27d38b44e60b1d1653c0dbf12199fe80d59/corelib/src/integer.cairo#L1066-L1116) and use `.expect("useful error message")` on the result

done, i think you meant those functions

**Comment by LucasLvy** [comment]
No i was referring to the functions i linked (`u256_overflowing_add`,`u256_overflowing_sub` etc)

**Comment by delaaxe** [comment]
those are clumsier to use, the checked ones allow using expect more directly. unless i completely misunderstood what you wanted to do?

**Comment by LucasLvy** [comment]
`checked_add` calls `overflowing_add` so you get a small improvement. It shouldn't be hard to use just do
```rs
let (r, overflow) = u256_overflowing_add(lhs, rhs);
let r = r.expect("....");
```

**Comment by delaaxe** [comment]
the first result value is a `u256`, so there's no `expect` method on it. why reimplement a function that already exists (the checked one)?

**Comment by delaaxe** [comment]
@LucasLvy can you check please?

**Comment by LucasLvy** [comment]
correct leave that as it is

**Review by LucasLvy — APPROVED** [review]

**Comment by delaaxe** [comment]
Thanks boss

**Pull request merged**
