### PR TITLE
Implement SHA512

### PR DESCRIPTION
**Pull request by edisontim**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

Issue Number: #114 

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by LucasLvy** [comment]
still draft ?

**Comment by edisontim** [comment]
> still draft ?

The PR is good to go but I use the u512 Default trait from https://github.com/starkware-libs/cairo/pull/3366/files in it

**Comment by edisontim** [comment]
Changed to create u512 object instead of using Default. I can update the repo to v2.0.0-rc5 once it's out also

**Comment by edisontim** [comment]
@LucasLvy this isn't draft anymore :)

**Review by LucasLvy — APPROVED** [review]

**Pull request merged**
