### PR TITLE
feat(math): binary exp

### PR DESCRIPTION
**Pull request by milancermak**
Updating the `pow` impl to use binary exponentiation, which is cheaper. 

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [x] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

`pow` is O(n)

## What is the new behavior?

`pow` is O(log n)

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

I did a simple [benchmark](https://gist.github.com/milancermak/adf6c70cdd550155a754e335d92fcbf5). Stepwise performance is the same for a simple case, the greater the exponent the more efficient this new implementation is.

Added a testcase to check for the whole 2^N range.

FWIW, it's pretty much the same as `BitShift::fpow` 😁 but without the use of Bitwise ops.

### CODE REVIEW

**Review by LucasLvy — COMMENTED** [review]
I think that we want to keep slow pow for small numbers

**Comment by milancermak** [comment]
> slow pow for small numbers

What do you mean?

**Comment by LucasLvy** [comment]
@enitrat Were you the one saying that the slow power is more efficient than fast power ?

**Comment by enitrat** [comment]
yes but I didn't run the benchmarks yet. Basically the overhead cost brought by additional div/rem opérations outweigh the gains for small exponents

**Comment by milancermak** [comment]
Yeah, if the test runner can be trusted, the small exponents gas usage stays the same.

**Comment by LucasLvy** [comment]
ok you win let's merge it

**Review by LucasLvy — APPROVED** [review]

**Pull request merged**
