### PR TITLE
feat: add carmichael number checker

### PR DESCRIPTION
**Pull request by Soptq**
This PR adds Carmichael number checker.

## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

- checking whether a bumber is a Carmichael number.
- all tests are passed.

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by LucasLvy — CHANGES_REQUESTED** [review]
add more tests this is a bit light

**Comment by Soptq** [comment]
> add more tests this is a bit light

Thanks for the advice, more tests are added ;). Note that 561 is the smallest Carmichael number (later is 41041, which requires about 1 billion gas to check and is too time-consuming for testing).

**Comment by LucasLvy** [comment]
then is it really useful to have that function ?

**Comment by Soptq** [comment]
> then is it really useful to have that function ?

Indeed. The complexity of this function is too high for a smart contract. I think if someone really wants to check if a given number is a carmichael number, he/she can simply hard-coded carmichael numbers into a list and check if the given number is inside the list.

I will close this PR due to the low practicality.

**Pull request closed without merging**
