### PR TITLE
feat: generic byte reader support for sha256 reopen

### PR DESCRIPTION
**Pull request by sveamarcus**
## Pull Request type

See previous PR for details

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-
-
-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

### CODE REVIEW

**Comment by LucasLvy** [comment]
I Don't really like changing that. I'd rather keep a sha impl that works with `Array<u8>` directly

**Comment by sveamarcus** [comment]
Fair enough, although ByteArray will probably also need hashing from time to time.

Should I port the reading enhancements over to the Array implementation? Saves over 15% gas cost.

**Comment by LucasLvy** [comment]
what exactly are the changes ? Note that less gas consumption doesn't necessarily equals to less steps

**Comment by sveamarcus** [comment]
Yes, I am aware of the discrepancy between gas cost and proof steps. In this case there is a probable blowup by the amount of data that is rewritten.

In main function `fn sha256(mut data: Array<u8>) -> Array<u8>`, there is a call to `from_u8Array_to_u32Array(data.span())`. This in turn copies the full data array into a new u32 array which is the sha256 block size. In this PR using `ByteReader` semantics the block data is dynamically read out from source byte data. Even though all data is accessed in both cases the additional cost of first creating an `Array<u32>` adds up to the significant difference.

**Comment by LucasLvy** [comment]
So yes please add your optimisations !

**Pull request closed without merging**
